# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    config.vm.define "docker-test" do |node|

        node.vm.box = "ubuntu/trusty64"
        node.vm.network "forwarded_port", guest: 80, host: 10080 #website
        node.vm.network "forwarded_port", guest: 8000, host: 18000 #website
        node.vm.network "forwarded_port", guest: 8001, host: 18001 #phpmyadmin
        node.vm.network "forwarded_port", guest: 1080, host: 11080 #mailcatcher
        node.vm.network "forwarded_port", guest: 8983, host: 18983 #SOLR
        node.vm.network "forwarded_port", guest: 18983, host: 18983 #SOLR
        node.vm.network "forwarded_port", guest: 3306, host: 13306 #MySQL
        node.vm.network "forwarded_port", guest: 5000, host: 15000
        node.vm.hostname = "docker-test.local"

        node.vm.synced_folder "../", "/var/www/docker-test"

        node.vm.provision :shell, path: "bootstrap.sh"

    end



end
